/* automatically generated by rust-bindgen 0.72.0 */

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct PgQueryError {
    pub message: *mut ::std::os::raw::c_char,
    pub funcname: *mut ::std::os::raw::c_char,
    pub filename: *mut ::std::os::raw::c_char,
    pub lineno: ::std::os::raw::c_int,
    pub cursorpos: ::std::os::raw::c_int,
    pub context: *mut ::std::os::raw::c_char,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct PgQueryProtobuf {
    pub len: usize,
    pub data: *mut ::std::os::raw::c_char,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct PgQueryScanResult {
    pub pbuf: PgQueryProtobuf,
    pub stderr_buffer: *mut ::std::os::raw::c_char,
    pub error: *mut PgQueryError,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct PgQueryProtobufParseResult {
    pub parse_tree: PgQueryProtobuf,
    pub stderr_buffer: *mut ::std::os::raw::c_char,
    pub error: *mut PgQueryError,
}
unsafe extern "C" {
    pub fn pg_query_scan(input: *const ::std::os::raw::c_char) -> PgQueryScanResult;
}
unsafe extern "C" {
    pub fn pg_query_parse_protobuf(
        input: *const ::std::os::raw::c_char,
    ) -> PgQueryProtobufParseResult;
}
unsafe extern "C" {
    pub fn pg_query_free_scan_result(result: PgQueryScanResult);
}
unsafe extern "C" {
    pub fn pg_query_free_protobuf_parse_result(result: PgQueryProtobufParseResult);
}
